"""Fail when the frontend's committed OpenAPI snapshot drifts from erserver's schema.

The frontend generates its TypeScript client types from a committed snapshot of
erserver's OpenAPI document (frontend/src/lib/api/openapi.json, regenerated by
`pnpm gen:api`). This check runs in the server CI job — the only job with the
server environment — and compares that snapshot byte-for-byte against the live
schema, so an API change cannot land without the reviewable frontend diff.

The generated schema.d.ts is derived from the snapshot by openapi-typescript, so
snapshot equality is the load-bearing half; a hand-edited schema.d.ts would be
caught by the frontend job's typecheck against real payloads, not here.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SNAPSHOT = REPO_ROOT / "frontend" / "src" / "lib" / "api" / "openapi.json"

# create_app() only reads settings; no connection is opened outside the lifespan.
os.environ.setdefault("ERSERVER_DSN", "postgresql://unused:unused@localhost:1/unused")

from erserver.api import create_app  # noqa: E402


def main() -> int:
    live = json.dumps(create_app().openapi(), sort_keys=True, indent=2) + "\n"
    if not SNAPSHOT.is_file():
        sys.stderr.write(f"{SNAPSHOT.relative_to(REPO_ROOT)} is missing\n")
        return 1
    if SNAPSHOT.read_text(encoding="utf-8") != live:
        sys.stderr.write(
            "frontend/src/lib/api/openapi.json is stale: erserver's schema changed.\n"
            "Regenerate and commit: cd frontend && corepack pnpm gen:api\n"
        )
        return 1
    print("frontend OpenAPI snapshot matches erserver")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
